### ISSUE TITLE
SkinFolderScript VisibleUrls Do Not Work

### ISSUE THREAD

**Issue by ElijahFowler** [JosephMDavis/mojoportal#8]
When ```RenderInPlace="true"``` ```VisibleUrls``` is not used.
When used by itself, it doesn't get rendered at all.

**Comment by JosephMDavis** [comment]
Issue has been fixed. visibleRoles was being checked instead of visibleUrls. When RenderInPlace was set to true, no checks against visibleRoles or visibleUrls were made.

**Comment by JosephMDavis** [comment]
Also enhanced the VisibleUrls option to check for a match with Page.AppRelativeVirtualPath so things like blog posts where the friendly url is something like /my-cool-post which is then mapped to the /Blog/ViewPost.aspx page. So, one could use /Blog/ViewPost.aspx in the AllowedUrls property to render a script on blog post pages.
